version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - consumer_some-net
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "1234"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - consumer_some-net

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    networks:
      - consumer_some-net

  app:
    build:
      context: .
      dockerfile: ./DistributedSystems/Dockerfile
    ports:
      - "8000:80"
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=db;Username=user;Password=1234"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - consumer_some-net
  
  consumer:
    build:
      context: .
      dockerfile: ./Consumer/Dockerfile
    ports:
      - "8001:80"
    networks:
      - consumer_some-net

networks:
  consumer_some-net: {
    driver: bridge
  }

volumes:
  pgdata:
  pgadmindata:
