# This is a generated file. Not intended for manual editing.
version: "3.9"
services:
  app:
    build:
      context: "/Users/kseniya/RiderProjects/DistributedSystems"
      dockerfile: "./DistributedSystems/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/DistributedSystems.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "distributedsystems:dev"
    ports: []
    volumes:
    - "/Users/kseniya/.nuget/packages:/root/.nuget/packages"
    - "/Users/kseniya/RiderProjects/DistributedSystems/DistributedSystems:/app:rw"
    - "/Users/kseniya/RiderProjects/DistributedSystems:/src:rw"
    working_dir: "/app"
  consumer:
    build:
      context: "/Users/kseniya/RiderProjects/DistributedSystems"
      dockerfile: "./Consumer/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/Consumer.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "consumer:dev"
    ports: []
    volumes:
    - "/Users/kseniya/.nuget/packages:/root/.nuget/packages"
    - "/Users/kseniya/RiderProjects/DistributedSystems/Consumer:/app:rw"
    - "/Users/kseniya/RiderProjects/DistributedSystems:/src:rw"
    working_dir: "/app"
